import type { KnowledgeRegistryClause } from "../knowledge-types";

const wf = (route: string, label: string) => ({ route, label });

export const ISO17065_CLAUSES: readonly KnowledgeRegistryClause[] = [
  {
    id: "17065-ca-structure",
    standardId: "ISO17065",
    clauseRef: "§4 stub",
    title: "Struktura tijela za certifikaciju proizvoda/procesa",
    summary: "Organizacijski preduvjeti neutralnosti i odgovornosti CA.",
    facets: ["management_system", "impartiality"],
    requirements: ["Pravno i organizacijski okvir CA.", "Politika nepristranosti."],
    controls: ["CA-STRUCT"],
    evidenceGuidance: ["Organogram", "Politike", "Imenovanja"],
    auditGuidance: ["Mapirajte odgovornosti na odluke i registre."],
    workflowMappings: [wf("/dashboard/iso/governance", "Governance")],
    governanceMappings: ["Uprava CA"],
    relatedRisks: ["RISK-CA-CONFLICT"],
    capaTriggers: ["Strukturalni sukob uloga"],
  },
  {
    id: "17065-scheme-development",
    standardId: "ISO17065",
    clauseRef: "§7 stub",
    title: "Razvoj sheme certifikacije",
    summary: "Transparentni zahtjevi, validacija sheme i kontrola izmjena.",
    facets: ["certification_decision", "management_system"],
    requirements: ["Verzioniranje sheme.", "Trag odobrenja."],
    controls: ["SCH-DEV"],
    evidenceGuidance: ["Verzije sheme", "Komentari odbora ili stručnjaka"],
    auditGuidance: [],
    workflowMappings: [wf("/dashboard/iso/schemes", "Sheme")],
    governanceMappings: [],
    relatedRisks: [],
    capaTriggers: [],
  },
  {
    id: "17065-complaints",
    standardId: "ISO17065",
    clauseRef: "§8 stub",
    title: "Pritužbe i žalbe (CA kontekst)",
    summary: "Postupci za pritužbe na certifikacijske odluke i uslugu.",
    facets: ["complaints", "appeals"],
    requirements: ["Objavljeni kanal", "Rokovi i zapis.", "Neovisnost."],
    controls: ["CMP-CA"],
    evidenceGuidance: ["Dossier", "Odgovori"],
    auditGuidance: ["Trend analiza pritužbi."],
    workflowMappings: [wf("/dashboard/iso/complaints", "Pritužbe"), wf("/dashboard/iso/appeals", "Žalbe")],
    governanceMappings: [],
    relatedRisks: [],
    capaTriggers: [],
  },
];
