import type { KnowledgeRegistryClause } from "../knowledge-types";

function c(x: KnowledgeRegistryClause): KnowledgeRegistryClause {
  return x;
}

const wf = (route: string, label: string) => ({ route, label });

/**
 * ISO/IEC 17024 — illustrative registry for UX (not exhaustive normative extraction).
 * Deepest registry in Phase G: impartiality, competence, exam, decision, surveillance,
 * recertification, appeals, complaints, MS.
 */
export const ISO17024_CLAUSES: readonly KnowledgeRegistryClause[] = [
  c({
    id: "17024-gen-legal",
    standardId: "ISO17024",
    clauseRef: "§4.1",
    title: "Pravni i ugovorni okvir certifikacije osobe",
    summary:
      "CB mora djelovati unutar pravno valjanog mandata; sheme i pravila certifikacije moraju biti javno dosupni u odgovarajućem opsegu.",
    facets: ["general", "management_system"],
    requirements: ["Definiran mandat i opseg certifikacije.", "Objava sheme i zahtjeva prema kandidatima."],
    controls: ["SHEMA-CTL", "MS-DOC-LEGAL-BASIS"],
    evidenceGuidance: ["Verzija sheme", "Objavljeni zahtjevi", "Ugovor/akreditacijski okvir (gdje primjenjivo)"],
    auditGuidance: ["Uzorkujte mapiranje sheme na proces odluke.", "Provjerite trag izmjena sheme."],
    workflowMappings: [wf("/dashboard/iso/schemes", "Sheme certifikacije")],
    governanceMappings: ["Upravljanje shemama", "Dokumentirana odobrenja sheme"],
    relatedRisks: ["RISK-SCOPE-DRIFT", "RISK-SCHEME-OBSOLETE"],
    capaTriggers: ["Neslaganje objavljenih zahtjeva s odlukama", "Istek mandata bez revizije sheme"],
  }),
  c({
    id: "17024-imp-struct",
    standardId: "ISO17024",
    clauseRef: "§5.1",
    title: "Struktura neutralnosti i nepristranosti",
    summary: "Organizacijski uvjeti koji štite nepristranost odluka o certifikaciji osobe.",
    facets: ["impartiality", "management_system"],
    requirements: ["Identificirane uloge i odgovornosti za integritet.", "Dokaz o odvojenosti prodaje i odluke (gdje primjenjivo)."],
    controls: ["IMP-POLICY", "IMP-COI-REGISTER"],
    evidenceGuidance: ["Politika nepristranosti", "Registar prijetnji", "COI izjave članova odbora"],
    auditGuidance: ["Provjerite zatvorenost COI prije odluka u uzorku.", "Povežite prijetnje s mitigacijama."],
    workflowMappings: [wf("/dashboard/iso/impartiality", "Nepristranost"), wf("/dashboard/iso/decisions", "Odluke odbora")],
    governanceMappings: ["Impartiality committee / owner", "Periodički pregled prijetnji"],
    relatedRisks: ["RISK-COI-LEAK", "RISK-COMM-PRESSURE"],
    capaTriggers: ["Otvoren COI tijekom odluke", "Ponavljajuće iste prijetnje bez mitigacije"],
  }),
  c({
    id: "17024-imp-threat-review",
    standardId: "ISO17024",
    clauseRef: "§5.2",
    title: "Analiza prijetnji nepristranosti",
    summary: "Sustavno otkrivanje i praćenje prijetnji uz aktivnosti certifikacije.",
    facets: ["impartiality"],
    requirements: ["Redovita analiza prijetnji i dokumentirani ishod.", "Veza prijetnje → kontrola → trag."],
    controls: ["IMP-THREAT-CYCLE"],
    evidenceGuidance: ["Zapisnici analize", "Ažurirani registar", "Veza na odluke odbora"],
    auditGuidance: ["Tražite trag zatvaranja prijetnji na uzorku odbora."],
    workflowMappings: [wf("/dashboard/iso/impartiality", "Registar prijetnji")],
    governanceMappings: ["Kvartalni / godišnji ciklus (prilagodite CB politici)"],
    relatedRisks: ["RISK-THREAT-STALE"],
    capaTriggers: ["Nedokumentirana ili zastarjela analiza prijetnji"],
  }),
  c({
    id: "17024-imp-committee-composition",
    standardId: "ISO17024",
    clauseRef: "§5.3",
    title: "Sastav odbora i neovisnost",
    summary: "Balans kompetencija i neovisnosti članova u odlučnim tijelima.",
    facets: ["impartiality", "certification_decision"],
    requirements: ["Kvorum i neovisnost u odnosu na kandidata.", "Dokumentiran rad i odluke."],
    controls: ["COMM-QUORUM", "COMM-MINUTES"],
    evidenceGuidance: ["Zapisnici", "Lista prisutnosti", "COI status pri glasanju"],
    auditGuidance: ["Za uzorak odluka provjerite trag COI i kvorum."],
    workflowMappings: [wf("/dashboard/iso/decisions", "Odluke"), wf("/dashboard/committee/pilot-applications", "Prijave odbora")],
    governanceMappings: ["Politika odbora", "Imenovanja"],
    relatedRisks: ["RISK-SINGLE-MEMBER-DEP"],
    capaTriggers: ["Odluka bez potpune kompozicije ili tragova"],
  }),
  c({
    id: "17024-comp-personnel",
    standardId: "ISO17024",
    clauseRef: "§6.1",
    title: "Kompetencija osoblja uključenog u certifikaciju",
    summary: "Uvjerenje u kompetenciju osoblja koje utječe na ispravnost certifikacije.",
    facets: ["competence", "management_system"],
    requirements: ["Kriteriji kompetencije", "Evidencija osposobljenosti i valjanosti."],
    controls: ["CMP-MATRIX", "CMP-REVIEW"],
    evidenceGuidance: ["Profili kompetencija", "Certifikati/edukacije", "Evaluacije", "Datumi isteka"],
    auditGuidance: ["Uzorkujte isteke i preslike odgovornosti."],
    workflowMappings: [wf("/dashboard/iso/competence", "Kompetencije")],
    governanceMappings: ["Godišnji pregled kompetencija"],
    relatedRisks: ["RISK-COMP-EXPIRY"],
    capaTriggers: ["Masovni isteci bez plana obnove"],
  }),
  c({
    id: "17024-comp-assessors",
    standardId: "ISO17024",
    clauseRef: "§6.2",
    title: "Ocjenjivači i neutralnost ocjenjivanja",
    summary: "Osiguravanje dosljednosti i nepristranosti ocjenjivača.",
    facets: ["competence", "impartiality"],
    requirements: ["Monitoriranje ocjenjivanja", "Rješavanje odstupanja u ocjenama."],
    controls: ["ASM-CALIBRATION"],
    evidenceGuidance: ["Rezultati kalibracije", "Kontrola uzoraka ocjena"],
    auditGuidance: ["Povežite assessor ID s COI stanjem i uzorkom odluka."],
    workflowMappings: [wf("/dashboard/iso/competence", "Kompetencije"), wf("/dashboard/iso/impartiality", "COI")],
    governanceMappings: ["Tehnički odbor / validacija (gdje postoji)"],
    relatedRisks: ["RISK-ASSESSOR-DRIFT"],
    capaTriggers: ["Ponavljana odstupanja bez CAPA"],
  }),
  c({
    id: "17024-exam-design",
    standardId: "ISO17024",
    clauseRef: "§7.1",
    title: "Ispit — dizajn i validacija",
    summary: "Ispit mora biti pouzdan, valjan i zaštićen od zlouporabe.",
    facets: ["examination"],
    requirements: ["Jasni ciljevi ispita", "Banka pitanja pod kontrolom verzija.", "Statistička / stručna validacija (prema shemi)."],
    controls: ["EXM-BANK-VER", "EXM-SAMPLE-CONTROL"],
    evidenceGuidance: ["Revizije banke", "Log promjena", "Zapis validacije"],
    auditGuidance: ["Provjerite verziju banke aktivne za sesiju."],
    workflowMappings: [wf("/dashboard/admin/item-bank", "Baza pitanja"), wf("/dashboard/exams", "Ispiti (portal)")],
    governanceMappings: ["Tehnički odbor — validacija"],
    relatedRisks: ["RISK-ITEM-LEAK"],
    capaTriggers: ["AI predlozi bez ljudske verifikacije gdje je obavezno"],
  }),
  c({
    id: "17024-exam-delivery",
    standardId: "ISO17024",
    clauseRef: "§7.2",
    title: "Ispit — provedba i integritet",
    summary: "Identitet kandidata, sigurnost sesije, trag rezultata.",
    facets: ["examination"],
    requirements: ["Integritet ispitnog okruženja", "Trag identiteta i rezultata."],
    controls: ["EXM-SESSION", "EXM-AUDIT-LOG"],
    evidenceGuidance: ["Logovi sustava", "Potpisi/verifikacije gdje postoje"],
    auditGuidance: ["Za uzorak pokušaja provjerite trag od otvaranja do ocjene."],
    workflowMappings: [wf("/dashboard/exams", "Ispiti")],
    governanceMappings: ["Politika proktoringa / lokacije"],
    relatedRisks: ["RISK-IDENTITY-WEAK"],
    capaTriggers: ["Anomalije u logovima ispita"],
  }),
  c({
    id: "17024-exam-grading",
    standardId: "ISO17024",
    clauseRef: "§7.3",
    title: "Ocjenjivanje i prijav rezultata",
    summary: "Dosljedna primjena rubrika i transparentan trag odluke o položio/ne.",
    facets: ["examination", "certification_decision"],
    requirements: ["Definirane rubrike", "Dvostruka kontrola gdje je predviđeno."],
    controls: ["GRD-RUBRIC", "GRD-REVIEW"],
    evidenceGuidance: ["Arhiva rezultata", "Pristupne kontrole"],
    auditGuidance: ["Provjerite presliku rubrika na ishod."],
    workflowMappings: [wf("/dashboard/exams", "Ispiti")],
    governanceMappings: [],
    relatedRisks: ["RISK-GRADE-BIAS"],
    capaTriggers: ["Žalbe kandidata na ispit (uzorak)"],
  }),
  c({
    id: "17024-cert-review",
    standardId: "ISO17024",
    clauseRef: "§8.1",
    title: "Pregled prijave i dokaznog paketa",
    summary: "Kompletnost dokaza prije odluke o certifikaciji.",
    facets: ["certification_decision"],
    requirements: ["Checkliste dokaza", "Neovisna provjera (gdje primjenjivo)."],
    controls: ["APP-REVIEW-TRACE"],
    evidenceGuidance: ["Status prijave", "Dokumenti", "Komentski trag"],
    auditGuidance: ["Uzorkujte prijave s negativnom odlukom i pozitivnom."],
    workflowMappings: [wf("/dashboard/iso/applications", "Prijave"), wf("/dashboard/committee/pilot-applications", "Odbor — prijave")],
    governanceMappings: [],
    relatedRisks: ["RISK-DOC-GAP"],
    capaTriggers: ["Nedostajući dokazi uz izdavanje certifikata (sistemski signal)"],
  }),
  c({
    id: "17024-cert-decision-trace",
    standardId: "ISO17024",
    clauseRef: "§8.2",
    title: "Odluka o certifikaciji — trag i dokumentacija",
    summary: "Odluka mora biti dokumentirana, obrazložena i povezana s shemom.",
    facets: ["certification_decision"],
    requirements: ["Zapis odluke", "Poveznica na ispit/kompetenciju gdje je relevantno."],
    controls: ["DEC-AUDIT-CHAIN"],
    evidenceGuidance: ["Zapisnik odbora", "Potpisi", "Verzija sheme"],
    auditGuidance: ["End-to-end trag od prijave do odluke na uzorku."],
    workflowMappings: [wf("/dashboard/iso/decisions", "Odluke")],
    governanceMappings: ["Politika odlučivanja"],
    relatedRisks: ["RISK-DECISION-OPAQUE"],
    capaTriggers: ["Odluke bez kompletnog traga"],
  }),
  c({
    id: "17024-cert-issuance",
    standardId: "ISO17024",
    clauseRef: "§8.3",
    title: "Izdavanje certifikata i javna vjerodostojnost",
    summary: "Registar certifikata, jedinstven identitet, verifikacija (gdje postoji).",
    facets: ["certification_decision"],
    requirements: ["Jedinstveni ID certifikata", "Kontrola dizajna i tiska (minimalno)."],
    controls: ["CERT-REGISTRY"],
    evidenceGuidance: ["Izdani dokument", "Zapis u registru", "Hash/javna provjera"],
    auditGuidance: ["Uskladite uzorak registra s fizičkim/digitalnim dokumentom."],
    workflowMappings: [wf("/dashboard/iso/certificates", "Registar"), wf("/verify", "Javna provjera")],
    governanceMappings: [],
    relatedRisks: ["RISK-DUPLICATE-CERT"],
    capaTriggers: ["Duplikat ili neusklađen dizajn"],
  }),
  c({
    id: "17024-surv-plan",
    standardId: "ISO17024",
    clauseRef: "§9.1",
    title: "Plan nadzora (surveillance)",
    summary: "Učestalost i metode nadzora usklađene sa shemom.",
    facets: ["surveillance"],
    requirements: ["Plan nadzora dokumentiran", "Obaviješteni certificirani."],
    controls: ["SURV-PLAN"],
    evidenceGuidance: ["Plan", "Obavijesti", "Izvješća"],
    auditGuidance: ["Provjerite uzorak certificiranih u planu."],
    workflowMappings: [wf("/dashboard/iso/certificates", "Registar")],
    governanceMappings: [],
    relatedRisks: ["RISK-SURV-MISSED"],
    capaTriggers: ["Preskočene periodicke aktivnosti"],
  }),
  c({
    id: "17024-surv-noncompliance",
    standardId: "ISO17024",
    clauseRef: "§9.2",
    title: "Nesukladnosti u nadzoru",
    summary: "Postupanje s nalazima nadzora do CAPA ili suspend/withdraw (prema politici).",
    facets: ["surveillance", "management_system"],
    requirements: ["Definirani koraci za nesukladnost", "Trag komunikacije."],
    controls: ["SURV-NC-ROUTE"],
    evidenceGuidance: ["Izvješće", "CAPA veza", "Odluka odbora ako je potrebna"],
    auditGuidance: ["Povežite NC iz nadzora s CAPA zatvaranjem."],
    workflowMappings: [wf("/dashboard/iso/capa", "CAPA")],
    governanceMappings: [],
    relatedRisks: ["RISK-NC-SILENT"],
    capaTriggers: ["Otvoreni nalazi bez akcijskog plana"],
  }),
  c({
    id: "17024-recert-triggers",
    standardId: "ISO17024",
    clauseRef: "§10.1",
    title: "Recertifikacija — okidači i dokazi",
    summary: "Nastavak kompetencije kontinuiranim profesionalnim razvojem ili ispitom (per shema).",
    facets: ["recertification", "competence"],
    requirements: ["Jasni kriteriji obnove", "Evidencija obnove."],
    controls: ["REC-CRITERIA"],
    evidenceGuidance: ["CPD slog", "Rezultati obnove", "Rokovi"],
    auditGuidance: ["Provjerite isteke i procese obnove u uzorku."],
    workflowMappings: [wf("/dashboard/admin/recertification", "Recertifikacije"), wf("/dashboard/my-recertifications", "Moja obnova")],
    governanceMappings: [],
    relatedRisks: ["RISK-RECERT-BACKLOG"],
    capaTriggers: ["Masovni isteci bez procesa"],
  }),
  c({
    id: "17024-recert-decision",
    standardId: "ISO17024",
    clauseRef: "§10.2",
    title: "Odluka o obnovi",
    summary: "Recertification odluka mora biti na istom integritetu kao inicijalna.",
    facets: ["recertification", "certification_decision"],
    requirements: ["Odbor/kompetentno tijelo", "Trag dokaza."],
    controls: ["REC-DEC-CHAIN"],
    evidenceGuidance: ["Paket obnove", "Odluka", "Obavijest"],
    auditGuidance: [],
    workflowMappings: [wf("/dashboard/iso/decisions", "Odluke")],
    governanceMappings: [],
    relatedRisks: [],
    capaTriggers: [],
  }),
  c({
    id: "17024-appeals-process",
    standardId: "ISO17024",
    clauseRef: "§11.1",
    title: "Postupak žalbe",
    summary: "Neovisno razmatranje žalbe na odluku o certifikaciji.",
    facets: ["appeals", "impartiality"],
    requirements: ["Rokovi i koraci", "Izbjegavanje sukoba interesa u žalbenom tijelu."],
    controls: ["APL-PROCESS"],
    evidenceGuidance: ["Dossier žalbe", "Odgovori", "Odluka žalbe"],
    auditGuidance: ["Provjerite neovisnost članova žalbenog tijela."],
    workflowMappings: [wf("/dashboard/iso/appeals", "Žalbe")],
    governanceMappings: ["Politika žalbi"],
    relatedRisks: ["RISK-APPEAL-BIAS"],
    capaTriggers: ["Žalbe s istim procesnim propustima"],
  }),
  c({
    id: "17024-appeals-records",
    standardId: "ISO17024",
    clauseRef: "§11.2",
    title: "Registri žalbi i trend analiza",
    summary: "Sistemsko učenje iz žalbi → CAPA / shema.",
    facets: ["appeals", "management_system"],
    requirements: ["Registar", "Periodički pregled trenda."],
    controls: ["APL-REG-TREND"],
    evidenceGuidance: ["Broj žalbi", "Kategorije", "Akcije"],
    auditGuidance: ["Povežite trend s izmjenama sheme ili CAPA."],
    workflowMappings: [wf("/dashboard/iso/appeals", "Žalbe")],
    governanceMappings: ["MR ulaz — žalbe"],
    relatedRisks: ["RISK-APPEAL-IGNORE"],
    capaTriggers: ["Rast žalbi bez analize"],
  }),
  c({
    id: "17024-comp-process",
    standardId: "ISO17024",
    clauseRef: "§12.1",
    title: "Pritužbe na proces i uslugu",
    summary: "Transparentan kanal, rokovi odgovora, veza na CAPA.",
    facets: ["complaints", "management_system"],
    requirements: ["Prijem prijava", "Klasifikacija", "Odgovor i trag."],
    controls: ["CMP-INTAKE"],
    evidenceGuidance: ["Tiketi", "Statusi", "Komunikacija"],
    auditGuidance: ["Uzorkujte zatvorene i otvorene prijave."],
    workflowMappings: [wf("/dashboard/iso/complaints", "Pritužbe"), wf("/dashboard/admin/support", "Operativna podrška")],
    governanceMappings: [],
    relatedRisks: ["RISK-COMPLAINT-SLA"],
    capaTriggers: ["Prekoračen rok odgovora (politika)"],
  }),
  c({
    id: "17024-comp-impartiality-link",
    standardId: "ISO17024",
    clauseRef: "§12.2",
    title: "Pritužbe i nepristranost",
    summary: "Analiza utjecaja pritužbe na integritet CB-a.",
    facets: ["complaints", "impartiality"],
    requirements: ["Poveznica na IMP registar kada sugerira prijetnju."],
    controls: ["CMP-IMP-LINK"],
    evidenceGuidance: ["Eskalacija", "IMP zapis"],
    auditGuidance: [],
    workflowMappings: [wf("/dashboard/iso/complaints", "Pritužbe"), wf("/dashboard/iso/impartiality", "IMP")],
    governanceMappings: [],
    relatedRisks: [],
    capaTriggers: [],
  }),
  c({
    id: "17024-ms-policy",
    standardId: "ISO17024",
    clauseRef: "§13.1",
    title: "Upravljački sustav — politika i ciljevi",
    summary: "CB MS pokriva certifikacijske aktivnosti i kontinuirano poboljšanje.",
    facets: ["management_system"],
    requirements: ["Politika kvalitete/integriteta", "Ciljevi i KPI (minimalno)."],
    controls: ["MS-POLICY"],
    evidenceGuidance: ["Dokumenti", "Odobrenja", "Distribucija"],
    auditGuidance: ["Provjerite verzije politika aktivne u uzorku datuma."],
    workflowMappings: [wf("/dashboard/iso/governance", "Governance")],
    governanceMappings: ["MR", "Kontrola dokumenata"],
    relatedRisks: ["RISK-POLICY-OBSOLETE"],
    capaTriggers: ["Istek pregleda politike"],
  }),
  c({
    id: "17024-ms-internal-audit",
    standardId: "ISO17024",
    clauseRef: "§13.2",
    title: "Interni audit program",
    summary: "Neovisna provjera usklađenosti MS i sheme.",
    facets: ["management_system"],
    requirements: ["Plan internih audit", "Implementacija i izvješća.", "Korektivne akcije."],
    controls: ["MS-IA-PROGRAM"],
    evidenceGuidance: ["Plan", "Checkliste", "Izvješća", "CAPA"],
    auditGuidance: ["Usporedite plan i stvarne zapise.", "Povežite nalazi s CAPA zatvaranjem."],
    workflowMappings: [wf("/dashboard/iso/audit", "Audit trag"), wf("/dashboard/iso/capa", "CAPA")],
    governanceMappings: [],
    relatedRisks: ["RISK-IA-WEAK"],
    capaTriggers: ["Plan neispunjen bez odobrenog razloga"],
  }),
  c({
    id: "17024-ms-management-review",
    standardId: "ISO17024",
    clauseRef: "§13.3",
    title: "Pregled rukovodstva",
    summary: "Ulazi iz rizika, CAPA, pritužbi, žalbi, audit — odluke i akcije.",
    facets: ["management_system"],
    requirements: ["Zapis pregleda", "Akcijski plani s vlasnicima i rokovima."],
    controls: ["MR-CYCLE"],
    evidenceGuidance: ["Zapisnik MR", "Akcije", "Statusi"],
    auditGuidance: ["Pratite zatvaranje akcijskog plana MR-a."],
    workflowMappings: [wf("/dashboard/iso/management-review", "MR")],
    governanceMappings: ["Kvartalni / godišnji ciklus"],
    relatedRisks: ["RISK-MR-THEATRICAL"],
    capaTriggers: ["Otvorene MR akcije dugo bez napretka"],
  }),
  c({
    id: "17024-ms-doc-control",
    standardId: "ISO17024",
    clauseRef: "§13.4",
    title: "Kontrola dokumenata i zapisa",
    summary: "Verzije, distribucija, zaštita i zadržavanje.",
    facets: ["management_system"],
    requirements: ["Klasifikacija dokumenata", "Trag odobrenja.", "Politika zadržavanja."],
    controls: ["DOC-CONTROL", "RETENTION-MAP"],
    evidenceGuidance: ["Verzije", "Metapodaci", "Pristupne kontrole"],
    auditGuidance: ["Za odluku provjerite koja je verzija procedure aktivna."],
    workflowMappings: [wf("/dashboard/iso/governance", "Governance dokumenti")],
    governanceMappings: [],
    relatedRisks: ["RISK-WRONG-DOC-VERSION"],
    capaTriggers: ["Korištenje neodobrene procedure"],
  }),
  c({
    id: "17024-info-use-of-marks",
    standardId: "ISO17024",
    clauseRef: "§14 stub",
    title: "Korištenje certifikacijskih oznaka",
    summary: "Kontrola zlouporabe oznaka i obavijesti certificiranima.",
    facets: ["certification_decision", "surveillance"],
    requirements: ["Upute za oznaku", "Postupanje uz zlouporabu."],
    controls: ["MARK-RULES"],
    evidenceGuidance: ["Ugovor/uvjeti", "Evidencija zlouporaba", "Korektivne mjere"],
    auditGuidance: ["Javni uzorak web stranica ili marketinških materijala."],
    workflowMappings: [wf("/dashboard/iso/certificates", "Registar")],
    governanceMappings: [],
    relatedRisks: ["RISK-MARK-MISUSE"],
    capaTriggers: ["Ponovljena zlouporaba"],
  }),
];
